---
title: "Study Areas SUMHAL"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: yeti
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
library('flexdashboard')
library('rgdal')
library("leaflet") 
library("leaflet.extras2")
library("sf")
library("tidyverse")
library("raster")
library("sp")
library("lubridate")
```


```{r baseMap}
map_base <- leaflet() %>%
  addWMSTiles(
    baseUrl = "http://www.ideandalucia.es/wms/mdt_2005?",
    layers = "Sombreado_10",
    group = "Hillshade",
    options = WMSTileOptions(
      format = "image/png", 
      transparent = TRUE),
    attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>'
  ) %>%
  addWMSTiles(
    baseUrl = "http://www.ign.es/wms-inspire/ign-base?",
    layers = "IGNBaseTodo",
    group = "Basemap",
    attribution = '© <a href="http://www.ign.es/ign/main/index.do" target="_blank">Instituto Geográfico Nacional de España</a>'
  ) %>%  
  addWMSTiles("http://www.ideandalucia.es/services/toporaster10/wms?",
    layers = "toporaster10",
    group = "Topographical",
    options = WMSTileOptions(
      format = "image/png", 
      transparent = FALSE),
    attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>'
  ) %>%
  addWMSTiles("http://www.ideandalucia.es/wms/mta10r_2001-2013?",
    layers = "mta10r_2001-2013",
    group = "topo2013",
    options = WMSTileOptions(
      format = "image/png", 
      transparent = FALSE),
    attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>'
  ) %>%
  leaflet.extras2::addWMS(
    baseUrl = "http://www.juntadeandalucia.es/medioambiente/mapwms/REDIAM_Montes_Publicos_Andalucia?",
    layers = "montes",
    group = "Montes Públicos",
    options =
      leaflet::WMSTileOptions(
        format = "image/png",
        transparent = TRUE,
        info_format = "text/html",
        tiled = FALSE
      )
  ) %>%
  leaflet.extras2::addWMS(
    baseUrl = "https://www.juntadeandalucia.es/medioambiente/mapwms/REDIAM_comunidades_vegetales?",
    layers = "Comunidades_vegetales",
    group = "Comunidades Vegetales",
    popupOptions = popupOptions(maxWidth = 1000),
    options =
      leaflet::WMSTileOptions(
        format = "image/png",
        transparent = TRUE,
        info_format = "text/html",
        opacity = 0.4,
        tiled = FALSE
      )
  ) %>%
  addProviderTiles("Esri.WorldImagery", group = "Satellite") %>% 
  addWMSTiles("http://www.ign.es/wms-inspire/pnoa-ma",
    layers = "OI.OrthoimageCoverage",
    group = "PNOA Máxima Actualidad",
    options = WMSTileOptions(
      format = "image/png", 
      transparent = FALSE),
    attribution = 'PNOA cedido por © <a href="http://www.ign.es/ign/main/index.do" target="_blank">Instituto Geográfico Nacional de España</a>'
  ) 
  

```





Sierra de las Nieves (SNI)
=============================================================================

```{r vege, eval=FALSE}
# Vegetation
veg_sni <- st_read("data/geo_pesadas/veg10/veg10_sni.shp", 
                   options = "ENCODING=UTF-8", quiet = TRUE)

veg <- st_transform(veg_sni, crs = 4326) %>% 
  dplyr::select(COM1, D_COM1, D_COM1_COB, D_CO1_ETAP,
                COM2, D_COM2, D_COM2_COB, D_CO2_ETAP,
                COM3, D_COM3, D_COM3_COB, D_CO3_ETAP,
                D_USO)


urlRediam <- "https://laboratoriorediam.cica.es/recursosVisor/pdfs/aplicacionVegetacion/COMU/"

tb <- ' target="_blank">'

popup_veg <- paste0(
  "<strong>Uso del Suelo:</strong> ", veg$D_USO,
  "<br><strong>Comunidad Predominante 1:</strong> ", paste0("<br><em>", veg$D_COM1, "</em>"),
  "<br>COD: ", paste0(
    "<a href=",
    paste0(urlRediam, veg$COM1, ".pdf"),
    tb,
    paste0(veg$COM1, "</a>")
  ),
  "<br>Cobertura: ", veg$D_COM1_COB,
  "<br>Etapa sucecional:",
  paste0("<br>", veg$D_CO1_ETAP),
  # Comunidad pred. 2
  "<br><strong>Comunidad Predominante 2:</strong> ",
  ifelse(veg$D_COM2 == "-", "",
    paste0("<br><em>", veg$D_COM2, "</em>")
  ),
  "<br>COD: ", ifelse(veg$COM2 == -1, "",
    paste0(
      "<a href=",
      paste0(urlRediam, veg$COM2, ".pdf"),
      tb,
      paste0(veg$COM3, "</a>")
    )
  ),
  "<br>Cobertura: ", ifelse(veg$D_COM2_COB == "Ausente", "", veg$D_COM2_COB),
  # Comunidad pred. 3
  "<br><strong>Comunidad Predominante 3:</strong> ",
  ifelse(veg$D_COM3 == "-", "",
    paste0("<br><em>", veg$D_COM3, "</em>")
  ),
  "<br>COD: ",
  ifelse(veg$COM3 == -1, "",
    paste0(
      "<a href=",
      paste0(urlRediam, veg$COM3, ".pdf"),
      tb,
      paste0(veg$COM3, "</a>")
    )
  ),
  "<br>Cobertura: ", ifelse(veg$D_COM3_COB == "Ausente", "", veg$D_COM3_COB)
)

```

```{r}
# Area of Interest 
aoi_sni <- st_read("data/aoi/aoi_sni.shp", quiet = TRUE) 
aoi_sni <- st_transform(aoi_sni, crs = 4326)
```


```{r lotes}
# Lotes
lotes <- st_read("data/lotes/lotes_sni.shp", quiet = TRUE)
lotes <- st_transform(lotes, crs = 4326)

popup_lotes <- paste0(
  "<strong>Nombre Lote:</strong> ", lotes$lote_name,
  "<br><strong>Zonas Rapca:</strong> ", lotes$zon_rapca,
  "<br><strong>Pastor:</strong> ", lotes$pastor
)

```


```{r}
# Set spatial extension 
myext <- st_bbox(aoi_sni) %>% as.vector()

map_base %>%
  fitBounds(myext[1], myext[2], myext[3], myext[4]) %>% 
  addPolygons(
    data = lotes,
    group = "Lotes",
    fillColor = "brown", fillOpacity = 0.4,
    stroke = TRUE, color= "brown", weight = 1,
    popup = popup_lotes,
    label = ~pastor,
    labelOptions = labelOptions(
      noHide = FALSE,
      offset = c(0, 0),
      textOnly = F,
      style = list("color" = "black")
    )
  ) %>% 
  addLayersControl(
    position = "bottomright",
    baseGroups = c("Basemap", "PNOA Máxima Actualidad", "Satellite", "Hillshade", "Topographical", "topo2013"),
    overlayGroups = c("Lotes", "Montes Públicos", "Comunidades Vegetales"), 
    options = layersControlOptions(collapsed = TRUE)
  )

```



Info
=============================================================================

**Visualización de las zonas potenciales de trabajo dentro del proyecto SUMHAL**

Las capas de información utilizadas son: 

- [Mapa Base](https://www.ign.es/web/ign/portal/ide-area-nodo-ide-ign) IGN (WMS)
- Catálogo de [Montes Públicos de Andalucía](https://laboratoriorediam.cica.es/geonetwork/srv/spa/catalog.search#/metadata/200b738b2a237099142a4bd263ceef957c8cdb07) (WMS)
- [Comunidades Vegetales de Andalucía 1:10000](https://laboratoriorediam.cica.es/geonetwork/srv/spa/catalog.search#/metadata/08bfb47f8052ebfd936c20c5509b85c3fc73a91b) (WMS)




